#!/usr/bin/env python3
"""Generate corrected ArtiSynth quantitative figures and Table S3 source.

The script refuses unvalidated inputs. It does not assume monotonicity and plots
all nine scales, including 0.80 and 0.85. Each output is a separate figure file
rather than a hidden/manual composite.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Mapping

from artisynth_common_CURRENT import (
    AMPLITUDES,
    FREQUENCIES,
    MODES,
    SCALES,
    SPEC_VERSION,
    SUCCESS,
    atomic_write_csv,
    atomic_write_json,
    atomic_write_text,
    read_csv_rows,
    sha256_file,
    utc_now,
)

SCRIPT_PATH = Path(__file__).resolve()


def load_validation(path: Path, fixed: Path, force: Path) -> dict[str, Any]:
    report = json.loads(path.read_text(encoding="utf-8"))
    if report.get("status") != "PASS" or report.get("spec_version") != SPEC_VERSION:
        raise ValueError("validation report is not a PASS for the canonical specification")
    if report.get("fixed_sha256") != sha256_file(fixed):
        raise ValueError("validation report fixed-table hash does not match input")
    if report.get("force_scaled_sha256") != sha256_file(force):
        raise ValueError("validation report force-scaled-table hash does not match input")
    return report


def float_or_nan(value: Any) -> float:
    try:
        x = float(value)
        return x if math.isfinite(x) else math.nan
    except Exception:
        return math.nan


def load_long(path: Path, mode: str) -> list[dict[str, str]]:
    rows = read_csv_rows(path)
    if len(rows) != 342:
        raise ValueError(f"{mode}: expected 342 long-table rows, got {len(rows)}")
    for row in rows:
        if row.get("mode") != mode or row.get("return_status") != SUCCESS:
            raise ValueError(f"{mode}: noncanonical/failed row {row.get('run_id')}")
    return rows


def load_fmax(path: Path, fixed: Path, force: Path) -> list[dict[str, str]]:
    rows = read_csv_rows(path)
    if len(rows) != 36:
        raise ValueError(f"strict-prefix fmax table must have 36 rows; got {len(rows)}")
    expected_hash = {"fixed_force": sha256_file(fixed), "force_capacity_s2": sha256_file(force)}
    for row in rows:
        if row.get("spec_version") != SPEC_VERSION:
            raise ValueError("fmax table spec_version mismatch")
        if row.get("source_long_table_sha256") != expected_hash[row["mode"]]:
            raise ValueError(f"fmax source hash mismatch for {row['mode']}")
        if row.get("prefix_rule_id") != "STRICT_ALL_LOWER_AND_SELF_FEASIBLE_V1":
            raise ValueError("fmax table was not generated by the strict-prefix rule")
    return rows


def ftag(value: float) -> str:
    return f"{value:.1f}".replace(".", "p")


def mode_label(mode: str) -> str:
    return "Fixed maximum force" if mode == "fixed_force" else "Maximum force scaled as s²"


def plot_fmax(rows: list[dict[str, str]], amplitude: float, out: Path) -> list[Path]:
    import matplotlib.pyplot as plt

    selected = [r for r in rows if abs(float(r["target_amp_p2p_mm"]) - amplitude) < 1e-9]
    fig, ax = plt.subplots(figsize=(6.5, 4.6))
    for mode in MODES:
        sub = sorted((r for r in selected if r["mode"] == mode), key=lambda r: float(r["scale"]))
        x = [float(r["scale"]) for r in sub]
        y = [float_or_nan(r["fmax_hz"]) for r in sub]
        ax.plot(x, y, marker="o", label=mode_label(mode))
        for r, xi, yi in zip(sub, x, y):
            if str(r.get("locally_nonmonotonic_feasibility", "")).lower() == "true" and math.isfinite(yi):
                ax.annotate("†", (xi, yi), xytext=(0, 6), textcoords="offset points", ha="center")
    ax.set_xlabel("Length-equivalent scale factor s")
    ax.set_ylabel("Strict-prefix maximum feasible frequency (Hz)")
    ax.set_title(f"Peak-to-peak target amplitude A = {amplitude:g} mm")
    ax.set_xticks([float(x) for x in SCALES])
    ax.set_xlim(0.78, 1.22)
    ax.set_ylim(0.8, 10.2)
    ax.grid(True, alpha=0.25)
    ax.legend(frameon=False)
    fig.tight_layout()
    paths = []
    for suffix in (".png", ".pdf"):
        p = out / f"Figure8_fmax_amp{ftag(amplitude)}_CURRENT{suffix}"
        fig.savefig(p, dpi=300, bbox_inches="tight")
        paths.append(p)
    plt.close(fig)
    return paths


def plot_heatmap(long_rows: list[dict[str, str]], cells_rows: list[dict[str, str]], *,
                 mode: str, amplitude: float, metric: str, label: str, out: Path) -> list[Path]:
    import matplotlib.pyplot as plt
    import numpy as np

    sub = [r for r in long_rows if r["mode"] == mode and abs(float(r["target_amp_p2p_mm"]) - amplitude) < 1e-9]
    lookup = {(float(r["scale"]), float(r["freq_hz"])): r for r in sub}
    ann = {(float(r["scale"]), float(r["freq_hz"])): r for r in cells_rows
           if r["mode"] == mode and abs(float(r["target_amp_p2p_mm"]) - amplitude) < 1e-9}
    scales = [float(x) for x in SCALES]
    freqs = [float(x) for x in FREQUENCIES]
    z = np.array([[float(lookup[(s, f)][metric]) for s in scales] for f in freqs], dtype=float)

    fig, ax = plt.subplots(figsize=(7.2, 5.3))
    image = ax.imshow(z, origin="lower", aspect="auto",
                      extent=(scales[0]-0.025, scales[-1]+0.025, freqs[0]-0.25, freqs[-1]+0.25))
    cbar = fig.colorbar(image, ax=ax)
    cbar.set_label(label)
    for s in scales:
        series = sorted((ann[(s, f)] for f in freqs), key=lambda r: float(r["freq_hz"]))
        fmax_vals = {float_or_nan(r["series_fmax_hz"]) for r in series}
        fmax_vals = {x for x in fmax_vals if math.isfinite(x)}
        if fmax_vals:
            y = next(iter(fmax_vals))
            ax.plot([s-0.022, s+0.022], [y, y], linewidth=2)
        for f in freqs:
            if str(ann[(s, f)]["cell_feasible_recomputed"]).lower() != "true":
                ax.text(s, f, "×", ha="center", va="center", fontsize=7)
    ax.set_xlabel("Length-equivalent scale factor s")
    ax.set_ylabel("Target frequency (Hz)")
    ax.set_title(f"{mode_label(mode)}; A = {amplitude:g} mm peak-to-peak")
    ax.set_xticks(scales)
    ax.set_yticks([1, 2, 4, 6, 8, 10])
    fig.tight_layout()
    metric_tag = "peak_excitation" if metric == "peak_excitation" else "mean_squared_excitation"
    paths = []
    for suffix in (".png", ".pdf"):
        p = out / f"SuppArtiSynth_{metric_tag}_{mode}_amp{ftag(amplitude)}_CURRENT{suffix}"
        fig.savefig(p, dpi=300, bbox_inches="tight")
        paths.append(p)
    plt.close(fig)
    return paths


def table_s3(fmax_rows: list[dict[str, str]], out: Path) -> tuple[Path, Path]:
    lookup = {(r["mode"], float(r["scale"]), float(r["target_amp_p2p_mm"])): r for r in fmax_rows}
    rows: list[dict[str, Any]] = []
    for amp in (float(x) for x in AMPLITUDES):
        for scale in (float(x) for x in SCALES):
            fixed = lookup[("fixed_force", scale, amp)]
            force = lookup[("force_capacity_s2", scale, amp)]
            ff = float_or_nan(fixed["fmax_hz"])
            fs = float_or_nan(force["fmax_hz"])
            rows.append({
                "target_amp_p2p_mm": amp,
                "scale": scale,
                "fixed_force_fmax_hz": None if not math.isfinite(ff) else ff,
                "force_capacity_s2_fmax_hz": None if not math.isfinite(fs) else fs,
                "force_minus_fixed_hz": None if not (math.isfinite(ff) and math.isfinite(fs)) else fs-ff,
                "fixed_first_failed_frequency_hz": fixed["first_failed_frequency_hz"],
                "fixed_first_failed_criterion": fixed["first_failed_criterion"],
                "force_capacity_s2_first_failed_frequency_hz": force["first_failed_frequency_hz"],
                "force_capacity_s2_first_failed_criterion": force["first_failed_criterion"],
                "fixed_locally_nonmonotonic": fixed["locally_nonmonotonic_feasibility"],
                "force_capacity_s2_locally_nonmonotonic": force["locally_nonmonotonic_feasibility"],
            })
    columns = list(rows[0])
    csv_path = out / "TableS3_CURRENT.csv"
    atomic_write_csv(csv_path, rows, columns)
    lines = [
        "% Generated only from validated corrected ArtiSynth outputs.",
        "\\begin{tabular}{rrrrr}",
        "\\toprule",
        "A (mm p2p) & $s$ & Fixed-force $f_{\\max}$ & Force $s^2$ $f_{\\max}$ & Difference \\\\",
        "\\midrule",
    ]
    for row in rows:
        def fmt(value: Any) -> str:
            if value is None or value == "": return "--"
            return f"{float(value):.1f}"
        lines.append(
            f"{row['target_amp_p2p_mm']:.1f} & {row['scale']:.2f} & "
            f"{fmt(row['fixed_force_fmax_hz'])} & {fmt(row['force_capacity_s2_fmax_hz'])} & "
            f"{fmt(row['force_minus_fixed_hz'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    tex_path = out / "TableS3_CURRENT.tex"
    atomic_write_text(tex_path, "\n".join(lines) + "\n")
    return csv_path, tex_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixed", type=Path, required=True)
    parser.add_argument("--force-scaled", type=Path, required=True)
    parser.add_argument("--fmax", type=Path, required=True)
    parser.add_argument("--cells-feasibility", type=Path, required=True)
    parser.add_argument("--validation-json", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        fixed = args.fixed.expanduser().resolve()
        force = args.force_scaled.expanduser().resolve()
        fmax_path = args.fmax.expanduser().resolve()
        cells_path = args.cells_feasibility.expanduser().resolve()
        validation_path = args.validation_json.expanduser().resolve()
        load_validation(validation_path, fixed, force)
        fixed_rows = load_long(fixed, "fixed_force")
        force_rows = load_long(force, "force_capacity_s2")
        fmax_rows = load_fmax(fmax_path, fixed, force)
        cells_rows = read_csv_rows(cells_path)
        if len(cells_rows) != 684 or any(r.get("spec_version") != SPEC_VERSION for r in cells_rows):
            raise ValueError("cell-feasibility table is not the canonical 684-row output")
        out = args.out_dir.expanduser().resolve()
        out.mkdir(parents=True, exist_ok=True)
        outputs: list[Path] = []
        for amp in (float(x) for x in AMPLITUDES):
            outputs += plot_fmax(fmax_rows, amp, out)
            for mode, long_rows in (("fixed_force", fixed_rows), ("force_capacity_s2", force_rows)):
                outputs += plot_heatmap(long_rows, cells_rows, mode=mode, amplitude=amp,
                                        metric="peak_excitation", label="Peak excitation", out=out)
                outputs += plot_heatmap(long_rows, cells_rows, mode=mode, amplitude=amp,
                                        metric="mean_summed_squared_excitation",
                                        label="Mean summed-squared excitation", out=out)
        table_paths = table_s3(fmax_rows, out)
        outputs += list(table_paths)
        metadata = {
            "spec_version": SPEC_VERSION, "generated_utc": utc_now(),
            "script": str(SCRIPT_PATH), "script_sha256": sha256_file(SCRIPT_PATH),
            "inputs": {
                "fixed": {"path": str(fixed), "sha256": sha256_file(fixed)},
                "force_scaled": {"path": str(force), "sha256": sha256_file(force)},
                "fmax": {"path": str(fmax_path), "sha256": sha256_file(fmax_path)},
                "cells_feasibility": {"path": str(cells_path), "sha256": sha256_file(cells_path)},
                "validation": {"path": str(validation_path), "sha256": sha256_file(validation_path)},
            },
            "outputs": [{"path": str(p), "sha256": sha256_file(p)} for p in outputs],
            "interpretation_guardrails": [
                "No causal inference in humans.",
                "Scale is a length-equivalent model parameter, not a living-speaker mass/inertia measurement.",
                "All scales are shown; no monotonicity is imposed.",
            ],
        }
        atomic_write_json(out / "ARTISYNTH_FIGURE_PROVENANCE_CURRENT.json", metadata)
        atomic_write_text(out / "ARTISYNTH_FIGURE_ASSEMBLY_CURRENT.md",
            "# Corrected ArtiSynth figure source\n\n"
            "Each quantitative panel is emitted as a separate PNG/PDF. This avoids manual value transfer and "
            "allows the journal layout to combine panels without changing data. Table S3 includes strict-prefix "
            "values and first-failure provenance. All panels show every tested scale from 0.80 through 1.20.\n")
        print(json.dumps({"output_count": len(outputs), "out_dir": str(out)}, indent=2))
        return 0
    except Exception as exc:
        print(f"ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 20


if __name__ == "__main__":
    raise SystemExit(main())
